lb = ('Botafogo', 'Fortaleza', 'Cruzeiro', 'Palmeiras', 'Internacional', 'Fluminense', 'Grêmio', 'São paulo', 'Vasco da gama', 'Atlético-MG', 'Santos', 'Bragantino', 'Flamengo', 'Athletico-PR', 'Bahia', 'Goiás', 'Corinthias', 'Cuiabá', 'Coritiba', 'América-MG')
print('-='*15)
print(f'Lista de times do Brasileirão: {lb}')
print('-='*15)
print(f'Os cinco primeiros são {lb[:5]}')
print('-='*15)
print(f'Os quatro últimos são {lb[16:]}')
print('-='*15)
print(f'Times em ordem alfabética {sorted(lb)}')
print('-='*15)
print(f'O flamengo está {lb.index("Flamengo")}° posição')